### ISSUE TITLE
MCU Info::Ram size: wrong

### ISSUE THREAD

**Issue by elemhsb** [fpoussin/QStlink2#11]
Hi, the displaying  of the MCU Info -> RAM size for several STM32F4 µC like 405VG is wrong.
I changes the sram_size in devices.xml, but the flashing will fail (hang on 12%) after this.

**Comment by fpoussin** [comment]
Hey,
Actually the ram size is the ram quantity used by the loader's buffer, it just needs to be smaller than the physical ram size minus the loader size (2KB)

**Comment by fpoussin** [comment]
I renamed the sram size to buffer size in 1.2.0.
