### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by slavkoja** [fpoussin/QStlink2#14]
Please, add build instructions (on linux) and requirements list. For me it fails with missing QUsb, it seems as in your another repository, but i am not sure about it.

**Comment by fpoussin** [comment]
Thanks for the feedback, I'll add build instructions.

**Comment by fpoussin** [comment]
Build instructions added, let me know it this works for you.

**Comment by slavkoja** [comment]
It works (on Linux) :-)

**Comment by slavkoja** [comment]
More precise, it works with Qt4, IMO under Qt5 section is missing how to select Qt5. I have both libraries and it seems, that Qt4 is as default.

**Comment by fpoussin** [comment]
Updated.

**Comment by slavkoja** [comment]
Thanks :)

BTW, the zip and tar.gz files have empty QtUsb directory, it is intended?

**Comment by fpoussin** [comment]
No but this is a limitation of github.
