### ISSUE TITLE
Support for STM32L series 

### ISSUE THREAD

**Issue by wrlear** [fpoussin/QStlink2#18]
I see entries for STM32L05xx in the devices database, but the processor is not being recognized on a NUCLEO-L053 board

Thanks,
Bill

**Comment by fpoussin** [comment]
Can you provide some debug output?

**Comment by wrlear** [comment]
Sorry for the delayed response. Fighting other fires. I'll check debug output the next time I can get back to this project. 
Bill

**Comment by fpoussin** [comment]
Any update?

**Comment by wrlear** [comment]
Sorry for my lack of response. We replaced the L0 with an L1, and I have not been able to get back to this to recreate the problem.

I’ll try to reconnect the Nucleo L0 tomorrow and get more info for you.

 

Bill

**Comment by fpoussin** [comment]
Did you have time to retry?

**Comment by wrlear** [comment]
Fabien,

Again, I apologize for my delayed responses – Attached are the debug outputs from two tests. qstlink2 failed to connect to the NUCLEO_STM32L053  (stm32l053r8t6)  , but succeeded with a NUCLEO_STM32L152 (stm32l152ret6).

Both boards work with OpenOCD and with the windows stlink program

 

The tests were run on Ubuntu14.04 running in a VirtualBox VM on a Windows8.1 host.  I installed qstlink2 from your ppa:

$ sudo add-apt-repository ppa:fpoussin/ppa

$ sudo apt-get update

$ sudo apt-get install qstlink2

 

 

It shows it is version 1.2.0

 

I hope this helps,

Bill

**Comment by fpoussin** [comment]
Hi,

You should have V1.2.1 from the PPA.
Can you check why the version is incorrect? Maybe you are using a proxy.

**Comment by wrlear** [comment]
Ok, I just did an apt-get update and re-installed qstlink2.  I now have version 1.2.1  (I had done the previous install prior to first reporting the problem).

Unfortunately, I get the same problem (see attached output).  qstlink2 gets what appears to be a valid CoreID, but gets a ChipID of 0x00

 

Bill

**Comment by fpoussin** [comment]
I fixed the problem (in theory), please update with apt in a few minutes.

**Comment by wrlear** [comment]
Ahh, much better!  V1.2.2 now correctly reports ChipID 0x417, device type STM32L05xx with 64KB flash.

 

Thanks.  

Bill

**Comment by fpoussin** [comment]
Perfect, I am closing the ticket.

Please re-open it if you encounter any other issues.
