### ISSUE TITLE
Build Error --- commit e95d5f9315073daaac875896213c4de4a2d33aa8

### ISSUE THREAD

**Issue by navesta** [fpoussin/QStlink2#22]
On Ubunut 14.04, am getting build error:
1- export QT_SELECT=5
2-$ qmake
Project MESSAGE: Building version 1.2.1 for Qt 5.2.1
Project MESSAGE: Building QtUsb with LibUsb 1.0 support.

3- make
...
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE -D__QSTL_VER__="\"1.2.1\"" -DQUSB_LIBRARY -DQLIBUSB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -Iinc -IQtUsb/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -o qlibusb.o QtUsb/src/qlibusb.cpp
QtUsb/src/qlibusb.cpp: In member function ‘virtual void QUsbDevice::flush()’:
QtUsb/src/qlibusb.cpp:215:74: error: invalid use of member function (did you forget the ‘()’ ?)
     libusb_bulk_transfer(mDevHandle, mConfig.readEp, (uchar*)(buf.data()+read), 4096, &read_bytes, 25);
                                                                          ^
QtUsb/src/qlibusb.cpp: At global scope:
QtUsb/src/qlibusb.cpp:218:8: error: prototype for ‘qint64 QUsbDevice::read(QByteArray*, quint32)’ does not match any in class ‘QUsbDevice’
 qint64 QUsbDevice::read(QByteArray* buf, quint32 maxSize)
        ^
In file included from QtUsb/src/qlibusb.cpp:1:0:
QtUsb/src/qlibusb.h:27:12: error: candidate is: virtual qint32 QUsbDevice::read(QByteArray*, quint32)
     qint32 read(QByteArray* buf, quint32 maxSize);
            ^
QtUsb/src/qlibusb.cpp:272:8: error: prototype for ‘qint64 QUsbDevice::write(const QByteArray*, quint32)’ does not match any in class ‘QUsbDevice’
 qint64 QUsbDevice::write(const QByteArray* buf, quint32 maxSize)
        ^
In file included from QtUsb/src/qlibusb.cpp:1:0:
QtUsb/src/qlibusb.h:28:12: error: candidate is: virtual qint32 QUsbDevice::write(const QByteArray*, quint32)
     qint32 write(const QByteArray* buf, quint32 maxSize);
            ^
make: *** [qlibusb.o] Error 1
...

Cheers,

**Comment by fpoussin** [comment]
There was a an error with the QtUsb submodule revision.

Fixed.
