### ISSUE TITLE
PPA returns 404 not found for AMD64 architechture

### ISSUE THREAD

**Issue by mrmowgli** [fpoussin/QStlink2#23]
Adding your PPA in Ubuntu 14.04 LTS x86-64, returns an error on apt-get update.

    W: Failed to fetch https://launchpad.net/~fpoussin/+archive/ppa/dists/trusty/main/binary-amd64/Packages  HttpError404
    W: Failed to fetch https://launchpad.net/~fpoussin/+archive/ppa/dists/trusty/main/binary-i386/Packages  HttpError404

**Comment by fpoussin** [comment]
Looks like the url is wrong:
http://ppa.launchpad.net/fpoussin/ppa/ubuntu/dists/trusty/main/binary-amd64/

**Comment by fpoussin** [comment]
I just reinstalled the package and it went just fine.
