### ISSUE TITLE
STM32F469NIH6 Device not found

### ISSUE THREAD

**Issue by ferrim** [fpoussin/QStlink2#28]
Please can you add this device in the database?
Thank you and best regards,
Marcello

**Comment by ferrim** [comment]
Newbie question solved with a little hacking into the devices.xml file (chip_id 0x434)

**Comment by fpoussin** [comment]
Can you do a pull request with the fix? 

Thanks!

**Comment by fpoussin** [comment]
Closing this since code has been merged (#31)
