### ISSUE TITLE
QSTLink2 Incorrectly Identifies Nucleo-144 F207GZ Board and Fails to Program it

### ISSUE THREAD

**Issue by RatGit** [fpoussin/QStlink2#30]
Unfortunately, QSTLink2 incorrectly reports my Nucleo-144 F207GZ board as a "STM32F405/415/407/417x" and when I program it with my generated "BIN" file it fails to execute.

Note: The same "BIN" file successfully downloads and executes when using the Windows STM32 ST-Link utility, (on a separate Windows machine)

Do you have any suggestions with regards to the QSTLink2 tool for Linux and the Nucleo-144 F207GZ board?

FYI:
I looked at the QSTLink2 "devices.xml" file and temporarily changed the "chip_id" value to "0x413" for the "STM32F2xx" device and commented out the "STM32F405/415/407/417x" device entry. After this the QSTLink2 utility successfully identified my board but still failed to program it successfully.

**Comment by fpoussin** [comment]
Did you use a release or code from the master branch?

**Comment by RatGit** [comment]
I used the PPA
