### ISSUE TITLE
STM32F4 Discovery locked after send .bin

### ISSUE THREAD

**Issue by vanbwodonk** [fpoussin/QStlink2#32]
I used st-flash on ubuntu 16.04, and i found this project. But at first try i cant upload .bin, qstlink2 hank in transfer progress. After that my STM32F4 discovery locked, i realize that after i cant upload .bin with st-flash anymore. Then in windows STlink - utility show flash locked in level 1.

**Comment by fpoussin** [comment]
Hi,

Did you use one of the releases or did you compile from the master branch ?

**Comment by vanbwodonk** [comment]
I compiled from master branch, try from release now.

**Comment by vanbwodonk** [comment]
OK my bad, successfully upload firmware after change to last release. Nice !!
Thanks,

**Comment by fpoussin** [comment]
Next time just use the ppa ;)
https://launchpad.net/~fpoussin/+archive/ubuntu/ppa
