### ISSUE TITLE
STM32F103x8 firmware uploading error

### ISSUE THREAD

**Issue by nerox8664** [fpoussin/QStlink2#36]
Firmware uploading stucks after "Loader uploaded".
It doesn't work with JTAG and with SWD  both.
So, I'm sure that it's not hardware/other problem, because i can properly upload firmware with st-util.

St-link:
Bus 001 Device 056: ID 0483:3748 STMicroelectronics ST-LINK/V2

Linux  4.10.11,
QStlink2 version  1.2.4

**Comment by fpoussin** [comment]
1.2.4 is not released yet, if you have the same issue with 1.2.3 see #33
