### ISSUE TITLE
Ubuntu PPA is out of date

### ISSUE THREAD

**Issue by Lanchon** [fpoussin/QStlink2#46]
- Bionic release is missing

please consider adding packages at least for LTS Ubuntu releases. some distros such as mint only depend on LTS, so with a little effort you can support a lot of people.

thank you!!!

**Comment by Lanchon** [comment]
oh, and thank you so much for this piece of software!!

**Comment by fpoussin** [comment]
Hi,
I made a copy for the Bionic release, it should be available in a few minutes.

**Comment by Lanchon** [comment]
awesome, its already there! thanks so much for the instant solution!!
