### ISSUE TITLE
Error Build in OSX Catalina 10.15.5

### ISSUE THREAD

**Issue by 4Joe** [fpoussin/QStlink2#52]
Could you update howto build for OSX?
Just try and error to build using a mac and got this error :
$ qmake
Project MESSAGE: Building version 1.3.0 for Qt 5.14.2
Project ERROR: Could not find hidapi-libusb using PKGCONFIG

how to resolve this error?

**Comment by fpoussin** [comment]
Try again with the latest master

**Comment by 4Joe** [comment]
great.. finally able to compile it on my mac
[qstlink2.app.zip](https://github.com/fpoussin/QStlink2/files/4856452/qstlink2.app.zip)
