### ISSUE TITLE
STM32F107 support

### ISSUE THREAD

**Issue by rasgo-cc** [fpoussin/QStlink2#7]
Is it possible to add support for STM32F107 micros?
Im currently using Olimex STM32 P107 development board and qstlink2 tells me that "Device not found in database!"

**Comment by Samed-Hamma** [comment]
Hi fpoussin, thanks very much for your effort before all !
I think it would be nice if you make a tutorial or add in README.md a "how to add a device by yourself".
Thanks !

**Comment by fpoussin** [comment]
Hi Samed, these are the USB IDs of your stlink, they have nothing to do with the actual core ids.
I'll add something in the readme.
